<?php $fupi_modules = [
    // order is important - modules will show up in this order in the side menu (except the 1st one which is hardcoded to always go 1st)!
    [   
        'name' => 'Modules',
        'id' => 'tools',
        'is_avail' => true,
        'is_premium' => false,
        'has_admin_page' => true,
        'is_addon' => false,
        'type' => 'home',
        'icon' => 'ext_ico2',
        'always_enabled' => true,
    ],
    [ 
        'name' => 'General Settings',
        'id' => 'main', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'home',
        'sticky_link' => true,
        'always_enabled' => true,
        // 'icon' => 'settings_ico2',
    ],
    [ 
        'name' => 'Crazy Egg',
        'id' => 'cegg', 
        'requires' => ['script_src'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true,
        'is_addon' => false,
        'type' => 'integr',
        'icon' => 'crazyegg_fav',
        'consents' => ['statistics', 'personalisation'],
        'check_gdpr' => true,
        'pp' => 'https://support.crazyegg.com/hc/en-us/articles/360054306594-Crazy-Egg-Privacy-Data-Practice',
    ],
    [ 
        'name' => 'Google Tag',
        'id' => 'gtag',
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr',
        'icon' => 'google_fav',
        'check_gdpr' => true,
    ],
    [ 
        'name' => 'Google Ads',
        'id' => 'gads',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr',
        'icon' => 'gads_fav',
        'check_gdpr' => true,
        'consents' => ['statistics', 'marketing'],
        'pp' => 'https://business.safety.google/privacy/'
    ],
    [ 
        'name' => 'Google Analytics',
        'id' => 'ga41',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr',
        'icon' => 'analytics_fav',
        'consents' => ['statistics'],
        'opt_consents' => ['marketing'],
        'check_gdpr' => true,
        'pp' => 'https://business.safety.google/privacy/'
    ],
    [ 
        'name' => 'Google Analytics #2',
        'id' => 'ga42',
        'requires' => ['id'],
        'is_avail' => fupi_fs()->can_use_premium_code(), 
        'is_premium' => true, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'consents' => ['statistics'],
        'opt_consents' => ['marketing'],
        'icon' => 'analytics_fav',
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://business.safety.google/privacy/'
    ],
    [ 
        'name' => 'Google Tag Manager',
        'id' => 'gtm',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr', 
        'icon' => 'gtm_fav',
        'check_gdpr' => true,
        'load_in_customizer' => true,
        'pp' => 'https://business.safety.google/privacy/'
    ],
    [ 
        'name' => 'Hotjar',
        'id' => 'hotj',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true,
        'consents' => ['statistics'],
        'icon' => 'hotjar_fav',
        'is_addon' => false,
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://help.hotjar.com/hc/en-us/articles/360009206234-General-Data-Protection-Regulation-GDPR',
    ],
    [ 
        'name' => 'Inspectlet',
        'id' => 'insp',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true,
        'consents' => ['statistics'],
        'is_addon' => false,
        'icon' => 'inspectlet_fav',
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://docs.inspectlet.com/hc/en-us/articles/360002994432-Privacy-Impact-Assessment-under-GDPR',
    ],
    [ 
        'name' => 'LinkedIn Insight',
        'id' => 'linkd',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics', 'marketing'],
        'is_addon' => false,
        'icon' => 'linkedin-fav',
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://www.linkedin.com/legal/privacy-policy#data',
    ],
    [ 
        'name' => 'Matomo',
        'id' => 'mato',
        'requires' => ['id', 'url'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics'],
        'is_addon' => false,
        'type' => 'integr', 
        'icon' => 'matomo_fav',
        'check_gdpr' => true,
        'pp' => 'https://matomo.org/matomo-cloud-privacy-policy/',
    ],
    [ 
        'name' => 'Meta Pixel',
        'id' => 'fbp1',
        'requires' => ['pixel_id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics', 'marketing'],
        'is_addon' => false,
        'type' => 'integr', 
        'icon' => 'meta_fav',
        'check_gdpr' => true,
        'pp' => 'https://www.facebook.com/privacy/policy/',
    ],
    [ 
        'name' => 'Microsoft Advertising',
        'id' => 'mads',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics', 'marketing'],
        'is_addon' => false,
        'type' => 'integr', 
        'icon' => 'microsoft_fav',
        'check_gdpr' => true,
        'pp' => 'https://help.ads.microsoft.com/apex/index/3/en/60212',
    ],
    [ 
        'name' => 'Microsoft Clarity',
        'id' => 'clar',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics'],
        'is_addon' => false,
        'type' => 'integr',
        'icon' => 'microsoft_fav',
        'check_gdpr' => true,
        'pp' => 'https://learn.microsoft.com/en-us/clarity/setup-and-installation/privacy-disclosure',
    ],
    [ 
        'name' => 'Pinterest Tag',
        'id' => 'pin',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics', 'marketing'],
        'is_addon' => false,
        'type' => 'integr', 
        'icon' => 'pinterest_fav',
        'check_gdpr' => true,
        'pp' => 'https://policy.pinterest.com/en-gb/privacy-policy-2018',
    ],
    [ 
        'name' => 'Plausible Analytics',
        'id' => 'pla',
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr', 
        'icon' => 'plausible_fav',
        'check_gdpr' => true,
    ],
    [ 
        'name' => 'PostHog',
        'id' => 'posthog',
        'requires' => ['api_key'],
        'is_avail' => true, 
        'is_premium' => false, 
        'consents' => ['statistics'],
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr', 
        'icon' => 'posthog_fav',
        'check_gdpr' => true,
        'pp' => 'https://posthog.com/handbook/company/security',
    ],
    [ 
        'name' => 'Simple Analytics',
        'id' => 'simpl',
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'icon' => 'simple_analytics-fav',
        'type' => 'integr',
        'check_gdpr' => false,
    ],
    [ 
        'name' => 'TikTok Pixel',
        'id' => 'tik',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics', 'marketing'],
        'is_addon' => false,
        'type' => 'integr', 
        'icon' => 'tiktok_fav',
        'check_gdpr' => true,
        'pp' => 'https://www.tiktok.com/legal/page/eea/privacy-policy/en',
    ],
    [ 
        'name' => 'X Ads (Twitter Ads)',
        'id' => 'twit',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'consents' => ['statistics', 'marketing'],
        'has_admin_page' => true, 
        'is_addon' => false,
        'icon' => 'x_ico',
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://x.com/en/privacy',
    ],
    [ 
        'name' => 'Custom Scripts',
        'id' => 'cscr', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr',
        'icon' => 'custom_scr_ico2',
        'load_in_customizer' => true,
        'check_gdpr' => 'always',
    ],
    [ 
        'name' => 'Shared tracking settings',
        'id' => 'track', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr',
        'always_enabled' => true,
        'sticky_link' => true,
        // 'dashicon' => 'dashicons-arrow-right-alt2',
    ],
    [ 
        'name' => 'Consent Banager',
        'id' => 'cook', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'priv', 
        'check_gdpr' => 'always',
        'icon' => 'cookie_icon2',
        'load_in_customizer' => true,
    ],
    [ 
        'name' => 'Records of Consent',
        'id' => 'proofrec', 
        'is_avail' => true,
        'is_premium' => false,
        'has_admin_page' => true,
        'is_addon' => false,
        'type' => 'priv', 
        'icon' => 'privex_ico2',
        'check_gdpr' => 'always',
    ],
    [ 
        'name' => 'Safe Fonts',
        'id' => 'safefonts', 
        'is_avail' => true,
        'is_premium' => false,
        'has_admin_page' => false,
        'is_addon' => false,
        'type' => 'priv', 
        'icon' => 'fonts_ico2',
        'check_gdpr' => 'always',
    ],
    [ 
        'name' => 'WooCommerce Tracking',
        'id' => 'woo', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'icon' => 'woo_fav',
        'type' => 'ext',
        'check_gdpr' => 'always',
    ],
    [ 
        'name' => 'Analytics Dashboards',
        'id' => 'reports', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true,
        'is_addon' => false,
        'icon' => 'reports_ico2',
        'type' => 'ext',
    ],
    [ 
        'name' => 'Advanced Triggers',
        'id' => 'atrig', 
        'is_avail' => fupi_fs()->can_use_premium_code(), 
        'is_premium' => true, 
        'has_admin_page' => true, 
        'icon' => 'adv_triggers_ico2',
        'is_addon' => false,
        'type' => 'ext', 
    ],
    [ 
        'name' => 'Geolocation',
        'id' => 'geo', 
        'is_avail' => fupi_fs()->can_use_premium_code(),
        'is_premium' => true, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'icon' => 'geo_ico2',
        'type' => 'ext',
    ],
];