<?php $fupi_modules = [
    // order is important - modules will show up in this order in the side menu (except the 1st one which is hardcoded to always go 1st)!
    // [
    //     'id' => 'home',
    //     'is_avail' => true, // can be used in current plan
    //     'is_premium' => false,
    //     'has_admin_page' => true,
    //     'is_addon' => false,
    //     'type' => 'settings',
    // ],
    [   
        'name' => 'Modules',
        'id' => 'tools',
        'is_avail' => true,
        'is_premium' => false,
        'has_admin_page' => true,
        'is_addon' => false,
        'type' => 'settings',
    ],
    [ 
        'name' => 'General Settings',
        'id' => 'main', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'settings',
    ],
    [ 
        'name' => 'Crazy Egg',
        'id' => 'cegg', 
        'requires' => ['script_src'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true,
        'is_addon' => false,
        'type' => 'integr',
        'consents' => ['statistics', 'personalisation'],
        'check_gdpr' => true,
        'pp' => 'https://support.crazyegg.com/hc/en-us/articles/360054306594-Crazy-Egg-Privacy-Data-Practice',
    ],
    [ 
        'name' => 'Google Ads',
        'id' => 'gads',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr',
        'check_gdpr' => true,
        'consents' => ['statistics', 'marketing'],
        'pp' => 'https://business.safety.google/privacy/'
    ],
    [ 
        'name' => 'Google Analytics',
        'id' => 'ga41',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr',
        'consents' => ['statistics'],
        'opt_consents' => ['marketing'],
        'check_gdpr' => true,
        'pp' => 'https://business.safety.google/privacy/'
    ],
    [ 
        'name' => 'Google Analytics #2',
        'id' => 'ga42',
        'requires' => ['id'],
        'is_avail' => fupi_fs()->can_use_premium_code(), 
        'is_premium' => true, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'consents' => ['statistics'],
        'opt_consents' => ['marketing'],
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://business.safety.google/privacy/'
    ],
    [ 
        'name' => 'Hotjar',
        'id' => 'hotj',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true,
        'consents' => ['statistics'],
        'is_addon' => false,
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://help.hotjar.com/hc/en-us/articles/360009206234-General-Data-Protection-Regulation-GDPR',
    ],
    [ 
        'name' => 'Inspectlet',
        'id' => 'insp',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true,
        'consents' => ['statistics'],
        'is_addon' => false,
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://docs.inspectlet.com/hc/en-us/articles/360002994432-Privacy-Impact-Assessment-under-GDPR',
    ],
    [ 
        'name' => 'LinkedIn Insight',
        'id' => 'linkd',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics', 'marketing'],
        'is_addon' => false,
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://www.linkedin.com/legal/privacy-policy#data',
    ],
    [ 
        'name' => 'Matomo',
        'id' => 'mato',
        'requires' => ['id', 'url'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics'],
        'is_addon' => false,
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://matomo.org/matomo-cloud-privacy-policy/',
    ],
    [ 
        'name' => 'Meta Pixel',
        'id' => 'fbp1',
        'requires' => ['pixel_id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics', 'marketing'],
        'is_addon' => false,
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://www.facebook.com/privacy/policy/',
    ],
    [ 
        'name' => 'Microsoft Advertising',
        'id' => 'mads',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics', 'marketing'],
        'is_addon' => false,
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://help.ads.microsoft.com/apex/index/3/en/60212',
    ],
    [ 
        'name' => 'Microsoft Clarity',
        'id' => 'clar',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics'],
        'is_addon' => false,
        'type' => 'integr',
        'check_gdpr' => true,
        'pp' => 'https://learn.microsoft.com/en-us/clarity/setup-and-installation/privacy-disclosure',
    ],
    [ 
        'name' => 'Pinterest Tag',
        'id' => 'pin',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics', 'marketing'],
        'is_addon' => false,
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://policy.pinterest.com/en-gb/privacy-policy-2018',
    ],
    [ 
        'name' => 'Plausible Analytics',
        'id' => 'pla',
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr', 
        'check_gdpr' => true,
    ],
    [ 
        'name' => 'PostHog',
        'id' => 'posthog',
        'requires' => ['api_key'],
        'is_avail' => true, 
        'is_premium' => false, 
        'consents' => ['statistics'],
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://posthog.com/handbook/company/security',
    ],
    [ 
        'name' => 'Simple Analytics',
        'id' => 'simpl',
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr',
        'check_gdpr' => true,
    ],
    [ 
        'name' => 'TikTok Pixel',
        'id' => 'tik',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'consents' => ['statistics', 'marketing'],
        'is_addon' => false,
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://www.tiktok.com/legal/page/eea/privacy-policy/en',
    ],
    [ 
        'name' => 'X Ads (Twitter Ads)',
        'id' => 'twit',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'consents' => ['statistics', 'marketing'],
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'integr', 
        'check_gdpr' => true,
        'pp' => 'https://x.com/en/privacy',
    ],
    [ 
        'name' => 'Google Tag Manager',
        'id' => 'gtm',
        'requires' => ['id'],
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'tagman', 
        'check_gdpr' => true,
        'load_in_customizer' => true,
        'pp' => 'https://business.safety.google/privacy/'
    ],
    [ 
        'name' => 'Custom Scripts',
        'id' => 'cscr', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'tagman',
        'load_in_customizer' => true,
        'check_gdpr' => true,
    ],
    [ 
        'name' => 'GDPR Setup Helper',
        'id' => 'status',
        'is_avail' => true,
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'priv',
        'custom_page_content' => true,
    ],
    [ 
        'name' => 'Consent Banner',
        'id' => 'cook', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'priv', 
        'check_gdpr' => true,
        'load_in_customizer' => true,
    ],
    [ 
        'name' => 'Iframes Manager',
        'id' => 'iframeblock', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'priv', 
        'check_gdpr' => true,
        'load_in_customizer' => true,
    ],
    [ 
        'name' => 'Safe Fonts',
        'id' => 'safefonts', 
        'is_avail' => true,
        'is_premium' => false,
        'has_admin_page' => false,
        'is_addon' => false,
        'type' => 'priv', 
        'check_gdpr' => true,
    ],
    [ 
        'name' => 'Privacy Policy Extras',
        'id' => 'privex', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'priv', 
        'check_gdpr' => true,
        'load_in_customizer' => true,
    ],
    [ 
        'name' => 'Tracking Tools Manager',
        'id' => 'blockscr', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'priv', 
        'check_gdpr' => true,
    ], 
    [ 
        'name' => 'WooCommerce Tracking',
        'id' => 'woo', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'ext',
    ],
    [ 
        'name' => 'Reports & Statistics',
        'id' => 'reports', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true,
        'is_addon' => false,
        'type' => 'ext',
    ],
    [ 
        'name' => 'Advanced Triggers',
        'id' => 'atrig', 
        'is_avail' => fupi_fs()->can_use_premium_code(), 
        'is_premium' => true, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'ext', 
    ],
    [ 
        'name' => 'Metadata Tracking',
        'id' => 'trackmeta', 
        'is_avail' => true, 
        'is_premium' => true, 
        'has_admin_page' => true, 
        'is_addon' => false ,
        'type' => 'ext',
    ],
    [ 
        'name' => 'Geolocation',
        'id' => 'geo', 
        'is_avail' => fupi_fs()->can_use_premium_code(),
        'is_premium' => true, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'ext',
    ],
    [ 
        'name' => 'Page labels',
        'id' => 'labelpages', 
        'is_avail' => true, 
        'is_premium' => true, 
        'has_admin_page' => false,
        'is_addon' => false,
        'type' => 'ext',
    ],
    [ 
        'name' => 'Broken Link Tracking',
        'id' => 'track404', 
        'is_avail' => true, 
        'is_premium' => false, 
        'has_admin_page' => true, 
        'is_addon' => false,
        'type' => 'ext',
    ],
];