<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_DIR', plugin_dir_path(dirname(__FILE__)));
define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_URL', plugin_dir_url(dirname(__FILE__)));

define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_DIR . 'includes' . DIRECTORY_SEPARATOR);
define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_ADMIN', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . 'admin' . DIRECTORY_SEPARATOR);
define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_FRONTEND', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . 'frontend' . DIRECTORY_SEPARATOR);
define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_LANGUAGES', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_DIR . 'languages' . DIRECTORY_SEPARATOR);
define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_TEMPLATES', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . 'templates' . DIRECTORY_SEPARATOR);
define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_COMPATIBLE', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . 'compatible' . DIRECTORY_SEPARATOR);

define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_CSS', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_URL . 'assets/css/');
define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_CSS_DIR', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_DIR . 'assets/css' . DIRECTORY_SEPARATOR);
define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_JS', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_URL . 'assets/js/');
define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_JS_DIR', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_DIR . 'assets/js' . DIRECTORY_SEPARATOR);
define('VI_WOO_PRODUCT_VARIATIONS_SWATCHES_IMAGES', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_URL . 'assets/images/');

/*Include functions file*/
if ( is_file( VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "functions.php" ) ) {
	require_once VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "functions.php";
}
if ( is_file( VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "support.php" ) ) {
	require_once VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "support.php";
}
if ( is_file( VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "data.php" ) ) {
	require_once VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "data.php";
}
vi_include_folder( VI_WOO_PRODUCT_VARIATIONS_SWATCHES_ADMIN, 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_Admin_' );
vi_include_folder( VI_WOO_PRODUCT_VARIATIONS_SWATCHES_FRONTEND, 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_Frontend_' );
vi_include_folder( VI_WOO_PRODUCT_VARIATIONS_SWATCHES_COMPATIBLE, 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_Compatible_' );
