<?php
/**
 * Template for the collapsible product category filter group.
 *
 * Wraps the per-product-type category trees in a single native <details> accordion.
 *
 * @var string $title Accordion label
 * @var string $tree_id Tree element ID prefix (hidden input name prefix)
 * @var string $description Section description
 * @var array $product_types [<prodTypeCode> => ['name' => string, 'selected_categories' => int[]], ...]
 */

use Comfino\View\SettingsForm;

if (!defined('ABSPATH')) {
    exit;
}
?>
<details class="comfino-filter-accordion" open>
    <summary style="cursor: pointer; font-size: 14px; font-weight: 600; padding: 8px 0;"><?php echo esc_html($title) ?></summary>
    <div style="padding: 8px 0 0 0;">
        <?php if (!empty($description)): ?>
            <p class="description"><?php echo esc_html($description) ?></p>
        <?php endif; ?>
        <?php foreach ($product_types as $productTypeCode => $productTypeData): ?>
            <h4><?php echo esc_html($productTypeData['name']) ?></h4>
            <?php
            // Output is safe HTML generated by TemplateManager::renderView() with values escaped internally.
            $category_tree_html = SettingsForm::renderCategoryTree(
                $tree_id,
                (string) $productTypeCode,
                $productTypeData['selected_categories']
            );
            echo $category_tree_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
            ?>
        <?php endforeach; ?>
    </div>
</details>
